import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./widgets";

export const metadata: Metadata = {
  title: "hawkingbros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {<Header />}
        {children}
      </body>
    </html>
  );
}
